### ISSUE TITLE
Error when running 'swift build' from Makefile

### ISSUE THREAD

**Issue by remko** [compnerd/gha-setup-swift#15]
I'm not sure if this is an issue with the action, or a general issue with SwiftPM on windows, so apologies if this is the wrong place to report this.

When I run `swift build` directly from within a GitHub action script, everything works fine.
However, when I have a rule in a Makefile that does a `swift build`, and run `make` (which is MingGW Make), I get the following error:

    error: unknown or missing subcommand 'swift-build.exe'

Any clue what could be going wrong, and how to fix this? Thanks!

**Comment by compnerd** [comment]
I don't think that this is the right place for that.  I think that the issue is likely that you are not running in the "x64 Native Tools Developer Command Prompt" and thus your environment is not setup correctly.  This is doubly so because you are using the MinGW make which I believe will use `bash` as the shell rather than `cmd`.

**Comment by remko** [comment]
@compnerd I see. Since it works in the cmd shell itself from which I call `make`, I was assuming any environment variables would be inherited by the child `make` environment (and bash descendants), but maybe this assumption is false.

**Comment by compnerd** [comment]
It isn't just about the environment variables but also about the shell.  The unknown or missing command implies that it didn't find `swift-build.exe` where it expected, which is likely due to running under bash and thus MinGW which changes the file system view.
