### ISSUE TITLE
'Package.swift has no Package.swift manifest' error

### ISSUE THREAD

**Issue by kelvin13** [compnerd/gha-setup-swift#8]
occasionally, my windows CI workflows fail with this error:

```
 https://github.com/kelvin13/swift-grammar @ 0.1.5: error: /\Package.swift has no Package.swift manifest for version 0.1.5 in https://github.com/kelvin13/swift-grammar
```

[full log](https://github.com/kelvin13/swift-json/runs/7533142213?check_suite_focus=true)

re-running the failed jobs usually succeeds.

[successful log](https://github.com/kelvin13/swift-json/runs/7533176047?check_suite_focus=true)

**Comment by compnerd** [comment]
This is not related to the action itself.  It is unclear if the problem is Foundation or tools-support-core (although it also could be a race condition in SPM).  There has been a fair amount of cleanup that went into tools-support-core, but there are a few outstanding changes still.  I suppose that we _could_ retry on the first failure, but that seems a bit heavy handed.  It would be preferable to actually fix the underlying issue(s).
